version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
  
  statsd_exporter:
    image: prom/statsd-exporter:v0.24.0
    container_name: statsd_exporter
    ports:
      - "9102:9102"
      - "9125:9125/udp"
    volumes:
      - ./statsd_exporter_config.yml:/etc/statsd-exporter/statsd_exporter_config.yml
    command:
      - '--statsd.mapping-config=/etc/statsd-exporter/statsd_exporter_config.yml'
  

volumes:
  prometheus_data:
  grafana_data: