global:
  scrape_interval: 10s
  scrape_timeout: 8s # should lower than scrape_interval
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'statsd_exporter'
    static_configs:
      - targets: ['statsd_exporter:9102']