defaults:
  summary_options:
    quantiles:
      - quantile: 0.99
        error: 0.001
      - quantile: 0.95
        error: 0.005
      - quantile: 0.9
        error: 0.01
      - quantile: 0.75
        error: 0.05
      - quantile: 0.5
        error: 0.05